### ISSUE TITLE
Create Block Struct

### ISSUE THREAD

**Issue by ahmadudin** [billysutomo/chocolate-waffle#24]
It would be easier if there is a structure that represents the Block entity. This entity could be used to simplify interface arguments too. Wdyt @billysutomo?

**Comment by billysutomo** [comment]
oke, let me prepare first. Later will update here for the data structure.

**Comment by billysutomo** [comment]
here is the data structure
```
{
  "id_project": 1,
  "ordernum": 1,
  "type": "messeger", // [messenger, block, social_link]
  "body": "{json}"
}
```

`id_project` project primary key
`ordernum` will be used for sorting block at frontend
`type` will be enum
`body` will be json, this data will be defined by frontend. so backend no need to parse.

**Comment by ahmadudin** [comment]
don't we need timestamp fields like `created_at`, `updated_at`, and `deleted_at`?

**Comment by billysutomo** [comment]
yeah, that is API design for POST method.
You asking for `Create Block Struct`, which is `POST` method right?

**Comment by ahmadudin** [comment]
Lol sorry for the ambiguous word. What i mean is we need the `Block` struct that represents it as an entity.

**Comment by billysutomo** [comment]
ahh I see. Ok I get it.
How about this
```
type Block struct {
	ID          int
	IDProject   int
	OrderNumber int
	Type        string
	Body        string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}
```

**Comment by ahmadudin** [comment]
Looks good to me :+1:

**Comment by billysutomo** [comment]
Done yah @ahmadudin
